# https://github.com/bennojoy/nginx
---
- name: install deps for apt_repository
  apt: >
    pkg={{ item }}
    state=latest
    update_cache=true
    cache_valid_time=3600
  with_items:
    - python-pycurl
    - python-apt
    # custom build with sticky
    # libgd2-noxpm
    # libgd2-xpm
    # libxslt1.1

- name: add nginx ppa
  apt_repository: >
    repo='deb http://ppa.launchpad.net/nginx/development/ubuntu precise main'

- name: add nodejs ppa key
  apt_key: >
    url='http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x00A6F0A3C300EE8C'

# we need to update_cache here
- name: install nginx 1.5.11-1+precise0
  apt: pkg="nginx=1.5.11-1+precise0"
       state=present
       update_cache=true

- name: copy the nginx configuration file
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
   - restart nginx

- name: create the configurations for sites (if present)
  template: >
    src=site.j2
    dest=/etc/nginx/conf.d/{{ item.server.file_name }}.conf
  with_items: nginx_sites
  when: nginx_sites|lower != 'none'
  notify:
   - reload nginx

- name: remove default site
  file: >
    state=absent
    path=/etc/nginx/sites-enabled/default
  notify:
   - reload nginx

- name: enable the nginx service
  service: >
    name=nginx
    state=started
    enabled=yes
