# https://github.com/bennojoy/nginx
---
- name: Install the nginx package
  apt: >
    name=nginx
    state=present
    update_cache=yes
    cache_valid_time=3600

- name: copy the nginx configuration file
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
   - restart nginx

- name: create the configurations for sites
  template: >
    src=site.j2
    dest=/etc/nginx/conf.d/{{item.server.file_name}}.conf
  with_items: nginx_sites
  when: nginx_sites|lower != 'none'
  notify:
   - reload nginx

- name: start the nginx service
  service: >
    name=nginx
    state=started
    enabled=yes
