---
- include: user.yaml

- name: install deps for building psycopg2
  apt: pkg={{item}}
       state=present
       update_cache=true
       cache_valid_time=3600
  with_items:
    - libpq-dev

- include: "{{inventory_dir}}/roles/common/tasks/virtualenv3.yaml"
  vars:
    virtualenv3_location: /home/cent/centrifuge/env33

- name: install centrifuge
  pip: >
    name=centrifuge
    state=present
    executable=/home/cent/centrifuge/env33/bin/pip

- name: copy over config.json
  template: >
    src=config.json.j2
    dest=/home/cent/centrifuge/config.json
    owner=cent
    group=cent
    mode=0640
