---
- hosts: all
  sudo: true
  roles:
    - common

- hosts: apppg
  sudo: true
  roles:
    - role: postgres
      pg_cfg_srv_listen_addresses: "{{ ansible_local.config.ip.private }}"
      pg_cfg_srv_listen_port: "{{ app_pg_port }}"
      pg_cfg_pg_hba_custom:
        - type: host
          database: "{{ app_pg_db_name }}"
          user: "{{ app_pg_db_user }}"
          address: "192.168.50.0/24"
          method: md5
          comment: "centrifuge structure database"
      pg_database_config:
        - database: "{{ app_pg_db_name }}"
          user: "{{ app_pg_db_user }}"
          password: "{{ app_pg_pass }}"

- hosts: appredis
  sudo: true
  roles:
    - role: redis

- hosts: centnode-01
  sudo: true
  gather_facts: false
  tasks:
    - command: cat /opt/centrifuge/wwc_project.ini
      register: wwc_project
    - set_fact: project_id="{{ wwc_project.stdout_lines[1].split(' ')[-1] }}"
    - set_fact: secret_key="{{ wwc_project.stdout_lines[2].split(' ')[-1] }}"

- hosts: appnode
  sudo: true
  vars:
    centrifuge_project_id: "{{ hostvars['centnode-01'].project_id }}"
    centrifuge_secret_key: "{{ hostvars['centnode-01'].secret_key }}"
    app_pg_host: "{{ hostvars['apppg-01'].ansible_local.config.ip.private }}"
  roles:
    - role: python
    - role: nodejs
    - role: app
      sqlalchemy_url: "postgresql+psycopg2://{{ app_pg_db_user }}:{{ app_pg_pass }}@{{ app_pg_host }}:{{ app_pg_port }}/{{ app_pg_db_name }}"
      redis_sessions_secret: "supersecret(plzchangeme!)"
      redis_sessions_host: "{{ redis_bind_address }}"
      redis_sessions_port: "{{ redis_port }}"
    - role: nginx
      nginx_use_epoll: true
      nginx_sites:
        - server:
            file_name: "wwc"
            listen: 80
            server_name: "{{ inventory_hostname }}"
            charset: "utf-8"
            location1:
              name: "/"
              uwsgi_pass: "unix://{{ uwsgi_socket_path }}/wwc.sock"
              include: "uwsgi_params"
              uwsgi_params:
                - "Host $host"
                - "X-Real-IP $remote_addr"
                - "X-Forwarded-For $proxy_add_x_forwarded_for"
                - "X-Forwarded-Proto $http_x_forwarded_proto"
            location2:
              name: "/static"
              root: "{{ app_location }}/wwc/wwc"
              expires: "30d"
              add_header: "Cache-Control public"
              access_log: "off"
            location3:
              name: "/app"
              root: "{{ app_location }}/"
              expires: "30d"
              add_header: "Cache-Control public"
              access_log: "off"
