---
- hosts: all
  sudo: true
  roles:
    - common

- hosts: centredis
  sudo: true
  vars:
    redis_bind_address: "{{ hostvars['centredis-1'].ansible_local.config.ip.private }}"
    redis_port: 6395
    redis_requirepass: true
    redis_pass: anotherbadone
  roles:
    - redis

- hosts: cent
  sudo: true
  vars:
    _pg_port: 5435
    _pg_pass: badpass!!
    _pg_db_name: cent_structure
    _pg_db_user: cent_structure
  roles:
    - role: centrifuge
      cent_conf:
        pg_host: "{{ hostvars['centlb-1'].ansible_local.config.ip.private }}"
        pg_port: "{{ _pg_port }}"
        pg_name: "{{ _pg_db_name }}"
        pg_password: "{{ _pg_pass }}"
        pg_user: "{{ _pg_db_user }}"
        redis_host: "{{ hostvars['centredis-1'].ansible_local.config.ip.private }}"
        redis_port: 6395
        redis_password: anotherbadone

- hosts: centlb
  sudo: true
  vars:
    _pg_port: 5435
    _pg_pass: badpass!!
    _pg_db_name: cent_structure
    _pg_db_user: cent_structure
  roles:
    - role: postgres
      pg_cfg_srv_listen_addresses: "{{ hostvars['centlb-1'].ansible_local.config.ip.private }}"
      pg_cfg_srv_listen_port: "{{ _pg_port }}"
      pg_cfg_pg_hba_custom:
        - type: host
          database: "{{ _pg_db_name }}"
          user: "{{ _pg_db_user }}"
          address: "192.168.50.0/24"
          method: md5
          comment: "centrifuge structure database"
      pg_database_config:
        - database: "{{ _pg_db_name }}"
          user: "{{ _pg_db_user }}"
          password: "{{ _pg_pass }}"
    - role: nginx
      nginx_sites: "none"

  tasks:
    - name: copy the centrifuge nginx configuration file
      template: >
        src=roles/nginx/templates/centrifuge.nginx.conf.j2
        dest=/etc/nginx/sites-available/centrifuge.nginx.conf
      notify:
        - reload nginx

    - name: create the link for site enabled specific configurations
      file: >
        path=/etc/nginx/sites-enabled/centrifuge.nginx.conf
        state=link
        src=/etc/nginx/sites-available/centrifuge.nginx.conf
      notify:
        - reload nginx
