---
- hosts: all
  sudo: true
  roles:
    - common

- hosts: centredis
  sudo: true
  roles:
    - redis

- hosts: cent
  sudo: true
  roles:
    - centrifuge

- hosts: centlb
  sudo: true
  roles:
    - role: postgres
      tester: badpass!!
      pg_cfg_pg_hba_custom:
        - { type: host, database: cent_structure, user: cent_structure, address: "192.168.50.0/24", method: md5, comment: "centrifuge structure database" }
      pg_database_config:
        - { database: cent_structure, user: cent_structure, password: "{{ tester }}" }
    - role: nginx
      nginx_sites: "none"

  tasks:
    - name: copy the centrifuge nginx configuration file
      template: >
        src=roles/nginx/templates/centrifuge.nginx.conf.j2
        dest=/etc/nginx/sites-available/centrifuge.nginx.conf
      notify:
        - reload nginx

    - name: create the link for site enabled specific configurations
      file: >
        path=/etc/nginx/sites-enabled/centrifuge.nginx.conf
        state=link
        src=/etc/nginx/sites-available/centrifuge.nginx.conf
      notify:
        - reload nginx
