---
- hosts: all
  sudo: true
  roles:
    - common

- hosts: centredis
  sudo: true
  vars:
    redis_bind_address: "{{ ansible_local.config.ip.private }}"
    redis_port: 6395
    redis_cluster_enabled: "yes"
    redis_cluster_node_timeout: 5000
    redis_appendonly: "yes"
  roles:
    - role: redis3
    - role: nginx
      nginx_sites: "none"
      nginx_max_clients: 1024
      nginx_use_epoll: true
      nginx_http_params:
        keepalive_timeout: "65"
        proxy_read_timeout: 200
        sendfile: "on"
        tcp_nopush: "on"
        tcp_nodelay: "on"
        gzip: "on"
        gzip_min_length: 1000
        gzip_proxied: "any"
        access_log: "/var/log/nginx/access.log"
        error_log: "/var/log/nginx/error.log"
        types_hash_max_size: 2048

  tasks:
    - name: copy the centrifuge nginx configuration file
      template: >
        src=roles/nginx/templates/centrifuge.nginx.conf.j2
        dest=/etc/nginx/sites-available/centrifuge.nginx.conf
      notify:
        - reload nginx

    - name: create the link for site enabled specific configurations
      file: >
        path=/etc/nginx/sites-enabled/centrifuge.nginx.conf
        state=link
        src=/etc/nginx/sites-available/centrifuge.nginx.conf
      notify:
        - reload nginx

#- hosts: cent
#  sudo: true
#  vars:
#    _pg_port: 5435
#    _pg_pass: badpass!!
#    _pg_db_name: cent_structure
#    _pg_db_user: cent_structure
#  roles:
#    - role: centrifuge
#      cent_conf:
#        pg_host: "{{ hostvars['centlb-1'].ansible_local.config.ip.private }}"
#        pg_port: "{{ _pg_port }}"
#        pg_name: "{{ _pg_db_name }}"
#        pg_password: "{{ _pg_pass }}"
#        pg_user: "{{ _pg_db_user }}"
#        redis_host: "{{ hostvars['centredis-1'].ansible_local.config.ip.private }}"
#        redis_port: 6395
#        redis_password: anotherbadone
#
#- hosts: centlb
#  sudo: true
#  vars:
#    _pg_port: 5435
#    _pg_pass: badpass!!
#    _pg_db_name: cent_structure
#    _pg_db_user: cent_structure
#  roles:
#    - role: postgres
#      pg_cfg_srv_listen_addresses: "{{ hostvars['centlb-1'].ansible_local.config.ip.private }}"
#      pg_cfg_srv_listen_port: "{{ _pg_port }}"
#      pg_cfg_pg_hba_custom:
#        - type: host
#          database: "{{ _pg_db_name }}"
#          user: "{{ _pg_db_user }}"
#          address: "192.168.50.0/24"
#          method: md5
#          comment: "centrifuge structure database"
#      pg_database_config:
#        - database: "{{ _pg_db_name }}"
#          user: "{{ _pg_db_user }}"
#          password: "{{ _pg_pass }}"
#    - role: nginx
#      nginx_sites: "none"
#
#  tasks:
#    - name: copy the centrifuge nginx configuration file
#      template: >
#        src=roles/nginx/templates/centrifuge.nginx.conf.j2
#        dest=/etc/nginx/sites-available/centrifuge.nginx.conf
#      notify:
#        - reload nginx
#
#    - name: create the link for site enabled specific configurations
#      file: >
#        path=/etc/nginx/sites-enabled/centrifuge.nginx.conf
#        state=link
#        src=/etc/nginx/sites-available/centrifuge.nginx.conf
#      notify:
#        - reload nginx
