---

- name: spin up a do droplet
  hosts: local

  tasks:
    - name: spin up 512mb 12.04.3 x64 in NYC 2
      digital_ocean: >
          state=present
          command=droplet
          name=do-1
          ssh_key_ids=62676,62594
          unique_name=yes
          virtio=yes
          private_networking=yes
          size_id=66
          region_id=4
          image_id=1505447
          wait_timeout=500
      register: my_droplet
    - debug: var=my_droplet.droplet.id
    - debug: var=my_droplet.droplet.ip_address

    - name: print out info
      debug: var=my_droplet
