---
nginx_max_clients: 512

nginx_http_params:
  sendfile: "on"
  tcp_nopush: "on"
  tcp_nodelay: "on"
  keepalive_timeout: "65"
  access_log: "/var/log/nginx/access.log"
  error_log: "/var/log/nginx/error.log"
  types_hash_max_size: 2048

nginx_sites: "none"

# example only
#- server:
#    file_name: bar
#    listen: 9090
#    server_name: ansible
#    root: "/tmp/site2"
#    location1:
#        name: /
#        try_files: "$uri $uri/ /index.html"
#    location2:
#        name: /images/
#        try_files: "$uri $uri/ /index.html"
