---
- name: install deps for apt_repository
  apt: >
    pkg={{ item }}
    state=latest
    update_cache=true
    cache_valid_time=3600
  with_items:
    - python-pycurl
    - python-apt

- name: add nodejs ppa
  apt_repository: >
    repo="deb {{ ppa }} precise main"

- name: add nodejs ppa key
  apt_key: >
    url="{{ ppa_key }}"

# we need to update_cache here
- name: install nodejs {{ ppa_version }}
  apt: >
    pkg="nodejs={{ ppa_version }}"
    state=present
    update_cache=true

- name: install bower
  npm: >
    name=bower
    global=yes
