---
- name: install all python 3 dependencies
  apt: pkg={{ item }}
       state=present
       update_cache=true
       cache_valid_time=3600
  with_items:
    - build-essential
    - python-dev
    - openssl
    - libssl-dev
    - libbz2-dev
    - zlib1g-dev
    - libexpat1-dev
    - libdb4.8-dev
    - libsqlite3-dev
    - libncursesw5-dev
    - libncurses5-dev
    - libreadline-dev
    - libxml2-dev
    - python-software-properties

- name: check for python {{ python_version }}
  shell: "[ -f /opt/python-{{ python_version}}/bin/python3.3 ]"
  register: python3
  ignore_errors: true
  changed_when: false

- name: download python {{ python_version }}
  command: >
    wget http://www.python.org/ftp/python/{{ python_version}}/Python-{{ python_version }}.tgz
    creates=/tmp/Python-{{ python_version }}.tgz
    chdir=/tmp/
  when: python3.rc

- name: untar Python-{{ python_version }}.tgz into /tmp directory
  command: >
    tar -xzvf /tmp/Python-{{ python_version }}.tgz
    chdir=/tmp
    creates=/opt/python-{{ python_version }}/bin/python3.3
  when: python3.rc

- name: configure Python-{{ python_version }}.tgz
  command: >
    ./configure --prefix=/opt/python-{{ python_version }}
    chdir=/tmp/Python-{{ python_version }}
    creates=/opt/python-{{ python_version }}/bin/python3.3
  when: python3.rc

- name: make Python-{{ python_version }}.tgz
  command: >
    make
    chdir=/tmp/Python-{{ python_version }}
    creates=/opt/python-{{ python_version }}/bin/python3.3
  when: python3.rc

- name: make install Python-{{ python_version }}.tgz
  command: >
    make install
    chdir=/tmp/Python-{{ python_version }}
    creates=/opt/python-{{ python_version }}/bin/python3.3
  when: python3.rc

- name: symlink python binaries to /usr/local/bin
  shell: >
    ln -s /opt/python-{{ python_version }}/bin/* /usr/local/bin
    creates=/usr/local/bin/python3
