---
- name: install deps for building psycopg2
  apt: pkg={{ item }}
       state=present
       update_cache=true
       cache_valid_time=3600
  with_items:
    - libpq-dev

- name: clone the wwc git repo
  git: >
    repo=https://github.com/dobrite/wwc.git
    dest="{{ app_location }}"

- name: make the environment
  shell: >
    PATH=$PATH:/opt/python-3.3.3/bin make env
    chdir="{{ app_location }}"

- name: set the sqlalchemy connection string in production.ini
  ini_file: >
    dest="{{ app_location }}/wwc/production.ini"
    section="app:main"
    option=sqlalchemy.url
    value="{{ sqlalchemy_url }}"

- name: set redis sessions secret in production.ini
  ini_file: >
    dest="{{ app_location }}/wwc/production.ini"
    section="app:main"
    option="redis.sessions.secret"
    value="{{ redis_sessions_secret }}"

- name: set redis sessions host in production.ini
  ini_file: >
    dest="{{ app_location }}/wwc/production.ini"
    section="app:main"
    option="redis.sessions.host"
    value="{{ redis_sessions_host }}"

- name: set redis sessions port in production.ini
  ini_file: >
    dest="{{ app_location }}/wwc/production.ini"
    section="app:main"
    option="redis.sessions.port"
    value="{{ redis_sessions_port }}"

- name: template out secrets.ini
  template: >
    src=secrets.ini.j2
    dest="{{ app_location }}/wwc/secrets.ini"
