---
- name: install deps for building psycopg2
  apt: pkg={{ item }}
       state=present
       update_cache=true
       cache_valid_time=3600
  with_items:
    - libpq-dev

- name: clone the wwc git repo
  git: >
    repo=https://github.com/dobrite/wwc.git
    dest="{{ app_location }}"

# XXX (we do this twice)
- name: give ownership to app
  command: >
    chown -R app:app {{ app_location }}

# XXX (this should only be a handler)
- name: make the app env
  sudo_user: app
  environment:
    HOME: "{{ app_location }}"
  shell: >
    make env
    chdir="{{ app_location }}"

- name: set the sqlalchemy connection string in production.ini
  ini_file: >
    dest="{{ app_location }}/wwc/production.ini"
    section="app:main"
    option=sqlalchemy.url
    value="{{ sqlalchemy_url }}"

- name: set redis sessions secret in production.ini
  ini_file: >
    dest="{{ app_location }}/wwc/production.ini"
    section="app:main"
    option="redis.sessions.secret"
    value="{{ redis_sessions_secret }}"

- name: set redis sessions host in production.ini
  ini_file: >
    dest="{{ app_location }}/wwc/production.ini"
    section="app:main"
    option="redis.sessions.host"
    value="{{ redis_sessions_host }}"

- name: set redis sessions port in production.ini
  ini_file: >
    dest="{{ app_location }}/wwc/production.ini"
    section="app:main"
    option="redis.sessions.port"
    value="{{ redis_sessions_port }}"

- name: template out secrets.ini
  template: >
    src=secrets.ini.j2
    dest="{{ app_location }}/wwc/secrets.ini"
