---
- include: user.yml
- include: app.yml
- include: uwsgi.yml

- name: give ownership to app
  command: >
    chown -R app:app {{ app_location }}

- name: start uwsgi-emperor
  service: >
    name=uwsgi-emperor
    state=started
