---
# upstart doesn't need enabled
- name: copy the uwsgi-emperor configuration file
  template: >
    src=uwsgi.emperor.upstart.j2
    dest=/etc/init/uwsgi-emperor.conf
  notify:
    - restart uwsgi-emperor

- name: create the log, conf, and socket directories
  file: >
    state=directory
    path="{{ item }}"
  with_items:
    - "{{ uwsgi_log_path }}"
    - "{{ uwsgi_config_path }}"
    - "{{ uwsgi_socket_path }}"

- name: copy the uwsgi configuration file
  template: >
    src=uwsgi.ini.j2
    dest="{{ uwsgi_config_path }}/uwsgi.ini"
