---
- name: restart ntp
  sudo: true
  service: >
    name=ntpd
    state=restarted

- name: restart iptables
  sudo: true
  service: >
    name=iptables
    state=restarted

- name: restart ssh
  sudo: true
  service: >
    name=ssh
    state=restarted
