---
redis_conf_dest: /etc/redis/redis.conf
redis_daemonize: "no"
redis_connection_timeout: 0
redis_tcp_keepalive: 0
redis_bind_address: "0.0.0.0"
redis_port: 6379
redis_loglevel: notice
redis_logfile: /var/log/redis/redis.log
redis_pidfile: /var/run/redis.pid
redis_syslog_enabled: "no"
redis_syslog_ident: redis
redis_syslog_facility: local0
redis_databases: 16
redis_database_save_times:
  - [900, 1]
  - [300, 10]
  - [60, 10000]
redis_dbfilename: dump.rdb
redis_db_dir: ./
redis_role: master
redis_requirepass: false
redis_pass: None
redis_max_clients: 128
redis_max_memory: 512mb
redis_maxmemory_policy: volatile-lru
redis_appendfsync: everysec
# if role is slave set these values too
redis_master_ip: 1.1.1.1
redis_master_port: 6379
redis_master_auth: None
