---
- name: create wwc database(s)
  sudo_user: postgres
  postgresql_db: >
    name={{ item.database }}
    state=present
    encoding={{ pg_encoding }}
    lc_collate={{ pg_locale }}
    lc_ctype={{ pg_locale }}
    login_host=localhost
    login_password={{ postgres_db_user_password }}
    port={{ pg_cfg_srv_listen_port }}
  with_items: pg_database_config
