---
- name: create postgres role(s)
  sudo_user: postgres
  postgresql_user: >
    user={{ item.user }}
    state=present
    password={{ item.password }}
    role_attr_flags=NOSUPERUSER,NOCREATEROLE,NOCREATEDB,NOINHERIT,NOREPLICATION
    login_host=localhost
    login_password={{ postgres_db_user_password }}
    port={{ pg_cfg_srv_listen_port }}
  with_items: pg_database_config
